/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'BKuczynski' at '07.06.16 11:30' with Gradle 2.13
 *
 * @author BKuczynski, @date 07.06.16 11:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
